{{ cookiecutter.project_name }}/config/urls.py
from django.conf import settings
from django.contrib.auth.views import (
  PasswordResetView,
  PasswordResetDoneView,
  PasswordResetConfirmView,
  PasswordResetCompleteView,
)
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path('contact/', TemplateView.as_view(template_name="pages/contact.html"), name="contact"),

    path('reset-password/', PasswordResetView.as_view(), name="password_reset"),
    path('reset-password/email-sent/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset-password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset-password/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('', TemplateView.as_view(template_name="pages/index.html"), name="index"),
    path('', include('{{ cookiecutter.project_name }}.users.urls', namespace="user")),
]

if settings.DEBUG:
  import debug_toolbar

  urlpatterns += [
    path('__debug__/', include(debug_toolbar.urls)),
  ]

  

{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = "user"

urlpatterns = [
  path('register/', views.UserCreateView.as_view(), name="register"),
  path('login/', views.UserLoginView.as_view(), name="login"),
  path('logout/', LogoutView.as_view(), name="logout"),
  path('~redirect/', views.UserRedirectView.as_view(), name="redirect"),
  path('<username>/', views.UserDetailView.as_view(), name="detail"),
  path('<username>/update-account/', views.UserUpdateView.as_view(), name="update_account"),
  path('<username>/delete-account/', views.UserDeleteView.as_view(), name="delete_account"),
  path('<username>/change-password/', views.UserPasswordChangeView.as_view(), name="password_change"),
]

{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
  first_name = models.CharField(max_length=30, verbose_name='first name')
  last_name = models.CharField(max_length=150, verbose_name='last name')
  email = models.EmailField(unique=True, verbose_name='email address')

  def get_absolute_url(self):
    return reverse("user:detail", kwargs={ "username": self.username })

  def __str__(self):
    return self.username

{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/users/forms.py
from django import forms as django_forms
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError

User = get_user_model()


class CreateUserForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = User
        fields = forms.UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
        )

    def clean_username(self):
        username = self.cleaned_data["username"].lower()

        if User.objects.filter(username=username).exists():
            raise ValidationError("Username has already been taken.")
        else:
            return username

    def clean_email(self):
        email = self.cleaned_data["email"].lower()

        if User.objects.filter(email=email).exists():
            raise ValidationError("Email has already been taken.")
        else:
            return email


class UpdateUserForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

    def clean_email(self):
        initial_email = self.initial["email"]
        cleaned_email = self.cleaned_data["email"].lower()

        if initial_email == cleaned_email:
            return cleaned_email
        elif User.objects.filter(email=cleaned_email).exists():
            raise ValidationError("Email has already been taken.")
        else:
            return cleaned_email

{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/users/views.py
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    FormView,
    RedirectView,
    UpdateView,
)
from .forms import CreateUserForm, UpdateUserForm

User = get_user_model()


class PermissionMixin(UserPassesTestMixin):
    """
  Mixin to see whether a user has permission or not. Permission will be granted
  if test_func returns True. If False, a permission error is raised.
  """

    def test_func(self):
        username = self.kwargs["username"]
        if username != self.request.user.username:
            return False
        else:
            return True


class UserCreateView(CreateView):
    template_name = "registration/register.html"
    form_class = CreateUserForm

    def get(self, request, *args, **kwargs):
        """ Redirect to detail page if user is logged in. """
        if request.user.is_authenticated:
            return redirect(reverse("user:detail", kwargs={"username": request.user}))
        else:
            return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        """ Login user after account is created. """
        form.save()
        username = self.request.POST["username"]
        password = self.request.POST["password2"]
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("user:detail", kwargs={"username": self.request.user})


class UserDetailView(DetailView):
    template_name = "users/detail.html"

    def get(self, request, *args, **kwargs):
        """ Only show profile if user is active. """
        user = self.get_object()
        if user.is_active:
            return super().get(request, *args, **kwargs)
        else:
            raise Http404("User does not exist!")

    def get_object(self, queryset=None):
        """ Prevent duplicate queries when retrieving object in other methods. """
        if not hasattr(self, "object"):
            username = self.kwargs["username"]
            user = get_object_or_404(User, username=username)
            self.object = user
        return self.object


class UserLoginView(LoginView):
    template_name = "registration/login.html"

    def get(self, request, *args, **kwargs):
        """ Redirect to detail page if user is logged in. """
        if request.user.is_authenticated:
            return redirect(reverse("user:detail", kwargs={"username": request.user}))
        else:
            return super().get(request, *args, **kwargs)


class UserRedirectView(LoginRequiredMixin, RedirectView):
    """ Used by LOGIN_REDIRECT_URL in settings/base.py """

    def get_redirect_url(self):
        return reverse("user:detail", kwargs={"username": self.request.user})


class UserUpdateView(LoginRequiredMixin, PermissionMixin, UpdateView):
    template_name = "users/update.html"
    form_class = UpdateUserForm

    def get_object(self, queryset=None):
        username = self.kwargs["username"].lower()
        user = get_object_or_404(User, username=username)
        return user


class UserDeleteView(LoginRequiredMixin, PermissionMixin, DeleteView):
    def get(self, request, *args, **kwargs):
        """ Soft deletion by changing user.is_active to False. """
        username = kwargs["username"]
        user = get_object_or_404(User, username=username)
        user.is_active = False
        user.save()
        messages.success(request, "User has been deleted.")
        return redirect(reverse("index"))


class UserPasswordChangeView(LoginRequiredMixin, PermissionMixin, PasswordChangeView):
    def get_success_url(self):
        messages.success(self.request, "Password has been changed.")
        return reverse("user:detail", kwargs={"username": self.request.user})

{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/templates/base.html
{% raw %}{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title%}{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
  <a href="{% url 'index' %}">Home</a> | 
  {% if request.user.is_authenticated %}
    <a href="{% url 'user:logout' %}">logout</a> |
    <span>current user: <a href="{% url 'user:detail' request.user %}">{{ request.user }}</a></span>
  {% else %}
    <a href="{% url 'user:login' %}">login</a> |
    <a href="{% url 'user:register' %}">register</a>
  {% endif %}
  <hr>
  {% if messages %}
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
  <hr>
  {% endif %}
  {% block content %}{% endblock content %}
</body>
</html>
{% endraw %}

{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/templates/pages/about.html
{% raw %}{% extends 'base.html' %}
{% block title %}About{% endblock title %}
{% block content %}
  <h1>ABOUT</h1>
{% endblock content %}
{% endraw %}

{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/templates/pages/contact.html
{% raw %}{% extends 'base.html' %}
{% block title %}Contact{% endblock title %}
{% block content %}
  <h1>CONTACT</h1>
{% endblock content %}
{% endraw %}

{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/templates/pages/index.html
{% raw %}{% extends 'base.html' %}
{% block title %}Index{% endblock title %}
{% block content %}
  <h1>HOME SWEET HOME</h1>
{% endblock content %}
{% endraw %}

{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/templates/users/detail.html
{% raw %}{% extends 'base.html' %}
{% block title %}{{ object }}{% endblock title %}
{% block content %}
  <h1>{{ object }}</h1>
  <ul>
    <li><strong>first name:</strong> {{ object.first_name }}</li>
    <li><strong>last name:</strong> {{ object.last_name }}</li>
    <li><strong>email:</strong> {{ object.email }}</li>
  </ul>

  {% if request.user == object %}
    <hr>
    <ul>
      <li><a href="{% url 'user:password_change' object %}">change password</a></li>
      <li><a href="{% url 'user:update_account' object %}">update account</a></li>
      <li><a href="{% url 'user:delete_account' object %}">delete account</a></li>
    </ul>
  {% endif %}
{% endblock content %}
{% endraw %}

{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/templates/users/update.html
{% raw %}{% extends 'base.html' %}
{% block title %}update {{ object }}{% endblock title %}
{% block content %}
  <h1>update {{ object }}</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}

    <p>{{ form.username.label }}</p>
    <p>{{ form.username.errors }}</p>
    <p>{{ form.username }}</p>

    <p>{{ form.first_name.label }}</p>
    <p>{{ form.first_name.errors }}</p>
    <p>{{ form.first_name }}</p>

    <p>{{ form.last_name.label }}</p>
    <p>{{ form.last_name.errors }}</p>
    <p>{{ form.last_name }}</p>

    <p>{{ form.email.label }}</p>
    <p>{{ form.email.errors }}</p>
    <p>{{ form.email }}</p>

    <input type="submit" value="Save changes">
  </form>
{% endblock content %}
{% endraw %}